// <auto-generated />
namespace DATOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class dbupdate1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbupdate1));
        
        string IMigrationMetadata.Id
        {
            get { return "201408260848592_dbupdate1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
