// <auto-generated />
namespace DATOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class canvis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(canvis));
        
        string IMigrationMetadata.Id
        {
            get { return "201410250458567_canvis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
