// <auto-generated />
namespace DATOS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class dbinit3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbinit3));
        
        string IMigrationMetadata.Id
        {
            get { return "201404091324013_dbinit3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
